# Generated by Django 5.0.7 on 2024-08-19 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicapi', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinicapi.doctor'),
        ),
    ]
