# Generated by Django 5.0.7 on 2024-09-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicapi', '0002_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirm', 'Confirm'), ('canceling', 'Canceling'), ('DONE', 'Done')], default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default='0705193E0423', max_length=12),
        ),
    ]
