# Generated by Django 5.0.7 on 2024-10-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicapi', '0003_alter_appointment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirm', 'Confirm'), ('canceling', 'Canceling'), ('done', 'Done')], default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default='955F06657260', max_length=12),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('appointment', 'Appointment'), ('medicine', 'Medicine'), ('invoice', 'Invoice'), ('general', 'General')], default='appointment', max_length=255),
        ),
    ]
