# Generated by Django 5.0.7 on 2024-10-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicapi', '0004_alter_appointment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default='2342847B9C2A', max_length=12),
        ),
    ]
