# Generated by Django 5.0.7 on 2024-10-04 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicapi', '0005_invoice_order_id_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinicapi.prescription'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default='89D08C70C45A', max_length=12),
        ),
    ]
