# Generated by Django 5.0.7 on 2024-10-05 17:16

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicapi', '0006_notification_prescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content2',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='news',
            name='image2',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='image3',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default='4EEA04CFC412', max_length=12),
        ),
    ]
