# Generated by Django 5.0.7 on 2024-10-11 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicapi', '0008_alter_invoice_invoice_number_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default='2B85B77D0A94', max_length=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinicapi.prescription'),
        ),
    ]
