# Generated by Django 5.0.7 on 2024-08-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicapi', '0009_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='unit',
            field=models.CharField(default='Viên', max_length=255),
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='count',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='price',
            field=models.FloatField(default=15000),
        ),
    ]
