# Generated by Django 5.0.7 on 2024-08-25 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicapi', '0011_notification_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='star',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
